
___

<a href='https://www.darshan.ac.in/'> <img src='https://gtu.darshan.ac.in/Upload/Logo/DIET_Logo.svg' /></a>
___
<pre>
<center><b>Python for Data Science - 3150713</b></center>
<center><b>Lab - 7</b></center>    
<pre>

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### import numpy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Output should be = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
b = np.ones(10)
b 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Output should be = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
c = np.ones(10)
c*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Output should be = array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
d = np.arange(10,51)
d 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Output should be = array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
e = np.arange(10,51,2)

Output should be = array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
d = np.arange(0,9)
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Output should be = <br/>
<pre>array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])</pre>

#### Create a 3x3 identity matrix

In [14]:
e = np.identity(3, dtype = float)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Output should be = <br/>
<pre>array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])</pre>

#### Use NumPy to generate a random number between 0 and 1

In [31]:
f = np.random.rand()
print(f)

0.8378942517100815


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
g = np.random.randint(1,100,25)
g

array([27, 52, 54, 97, 60, 21, 52, 86, 19, 29, 65, 30, 42, 60, 98, 25, 37,
       43, 56, 66, 98, 22, 63, 86, 40])

#### Create the following matrix:

In [71]:
h = np.arange(1,101)
i = h/100
i.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Output should be = <br/>[[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],<br/>
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],<br/>
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],<br/>
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],<br/>
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],<br/>
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],<br/>
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],<br/>
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],<br/>
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],<br/>
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]]

#### Create an array of 20 linearly spaced points between 0 and 1:

In [73]:
j = np.linspace(0, 1, 20)
j

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Slicing


In [75]:
k = np.arange(1,26)
l = k.reshape(5,5)
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Output should be = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [91]:
m = l[2:,1:] 
# m.reshape(3,4)
m

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Output should be = 
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

Output should be = 20 (element at specific index)

Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

Output should be = array([21, 22, 23, 24, 25])

Output should be =  <br/>
<pre>array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

Print all the number which are divisible by 3 but not by 5<br/>
Output should be = [ 3  6  9 12 18 21 24]

### Now do the following

#### Get the sum of all the values in mat

Output should be = 325

#### Get the standard deviation of the values in mat

Output should be = 7.211102550927978

#### Get the sum of all the columns in mat

Output should be = array([55, 60, 65, 70, 75])

# Convert image into gray scale

# Nice work, Keep the spark alive